services:
  web:
    image: vigneshwaraprabu/yii2-app:latest
    deploy:
      replicas: 1
    ports:
      - "9000:9000"
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  webnet:
